pytermor.exception
==================

.. automodule:: pytermor.exception

   
   
   

   
   
   

   
   
   

   
   
   .. rubric:: Exceptions

   .. autosummary::
   
      ArgTypeError
      ConflictError
      LogicError
      UserAbort
      UserCancel
   
   



